/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VirusScanner */

#ifndef _Included_VirusScanner
#define _Included_VirusScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VirusScanner
 * Method:    scanFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_VirusScanner_scanFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
